import { chromium } from '@playwright/test'
const browser = await chromium.launch()
const ctx = await browser.newContext()
const page = await ctx.newPage()
page.on('request', r => { if (r.url().includes('/api/auth')) console.log('[req]', r.method(), new URL(r.url()).pathname) })
page.on('response', r => { if (r.url().includes('/api/auth')) console.log('[resp]', r.status(), new URL(r.url()).pathname) })
await page.goto('http://localhost:3000/login')
await page.locator('input[type=email]').fill('admin@payrollpro.com')
await page.locator('input[type=password]').fill('admin123')
await page.locator('button[type=submit]').click()
await page.waitForURL(/dashboard/, { timeout: 25000 })
console.log('--- logged in → full reload to /employees (hard reload = session restore) ---')
await page.goto('http://localhost:3000/employees', { timeout: 40000 })
await page.waitForTimeout(3000)
const txt = await page.locator('body').innerText()
console.log('--- url:', page.url())
console.log('--- Session-refresh-failed? ', /Session refresh failed|refresh failed/i.test(txt))
console.log('--- has employee table? ', /Cari nama|karyawan/i.test(txt))
console.log('--- body head:', txt.slice(0,120).replace(/\n/g,' | '))
await browser.close()
