import { chromium } from '@playwright/test'
const browser = await chromium.launch()
const ctx = await browser.newContext()
const page = await ctx.newPage()
page.on('request', r => { const u=r.url(); if(u.includes('/api/')) net.push(`${r.method()} ${u.replace(/^http:\/\/[^/]+/,'')}`) })
page.on('response', r => { const u=r.url(); if(u.includes('/api/')) resps.push(`${r.status()} ${u.replace(/^http:\/\/[^/]+/,'')}`) })
page.on('console', m => { const t=m.text(); if(/refresh|Failed|error/i.test(t) && m.type()!=='warning') console.log('  [console]', t.slice(0,110)) })
await page.goto('http://localhost:3000/login')
await page.locator('input[type=email]').fill('admin@payrollpro.com')
await page.locator('input[type=password]').fill('admin123')
await page.locator('button[type=submit]').click()
await page.waitForURL(/dashboard/, { timeout: 25000 })
console.log('login OK ->', page.url())
console.log('=== goto /attendance/check-in (full reload, guard race territory) ===')
net.length=0; resps.length=0
await page.goto('http://localhost:3000/attendance/check-in', { timeout: 40000 })
await page.waitForTimeout(5000)
console.log('--- url AFTER 5s:', page.url())
const sel = page.locator('select').first()
console.log('--- option count:', await sel.locator('option').count())
console.log('--- net order:'); ; [...new Set(net)].forEach(l=>console.log('   ',l))
await browser.close()
